# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KkTz2OPE4L-20jcTmxubaHQwwAvivEsd
"""

!pip install pyLDAvis -q

!pip install kagglehub -q

import numpy as np                   # Matematiksel hesaplamalar ve dizi işlemleri için.
import pandas as pd                  # Verileri tablolar halinde yönetmek için.
import matplotlib.pyplot as plt      # Grafik çizdirmek için temel kütüphane.
import seaborn as sns                # Daha şık grafikler oluşturmak için.
from wordcloud import WordCloud      # Kelime bulutlarını oluşturmak için.
import re                            # Metin temizleme (link, sembol kaldırma) işlemleri için.
import os                            # Dosya yolu ve sistem işlemleri için.
from bs4 import BeautifulSoup        # HTML kodlarını metinden ayıklamak için.
from collections import Counter      # Kelime sayımları yapmak için.
import warnings                      # Gereksiz uyarı mesajlarını gizlemek için.


import nltk
from nltk import pos_tag, word_tokenize
from nltk.corpus import stopwords, wordnet
from nltk.stem import WordNetLemmatizer      # Kelime köklerini bulmak için.

# --- Makine Öğrenmesi ve Modelleme ---
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline        # İşlem adımlarını birbirine bağlar.
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer # Metni sayıya döker.
from sklearn.decomposition import LatentDirichletAllocation, NMF             # Konu bulma algoritmaları.
from joblib import dump

# --- Görselleştirme Araçları ---
import pyLDAvis
import pyLDAvis.lda_model

# Uyarıları kapatıyoruz
warnings.filterwarnings('ignore')




# Kelime köklerini bulma ve dilbilgisi analizi için gerekli paketler.
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('wordnet')
nltk.download('omw-1.4')



#  Veri Setinin İndirilmesi
import kagglehub
path = kagglehub.dataset_download("gpreda/bbc-news")
print("Veri setinin indirildiği yol:", path)


# Dosyaları listele
files = os.listdir(path)
print("Klasördeki dosyalar:", files)



# CSV dosyasını yüklüyoruz
df = pd.read_csv(f'{path}/bbc_news.csv')


df['Text'] = df['title'] + ' ' + df['description']



df = df.drop(columns=['title', 'pubDate', 'guid', 'link', 'description'])


# Yinelenen (kopya) verileri temizliyoruz
df = df.drop_duplicates()



#...





#  Metin Ön İşleme Fonksiyonları
def get_wordnet_pos(word):
    """Kelimelerin dilbilgisi etiketini (isim, fiil vb.) WordNet formatına çevirir."""
    tag = pos_tag([word])[0][1][0].upper()    #Kelimenin türünü al
    tag_dict = {
        'J': wordnet.ADJ,         # Sıfat
        'N': wordnet.NOUN,        # İsim
        'V': wordnet.VERB,        # Fiil
        'R': wordnet.ADV          # Zarf
    }
    return tag_dict.get(tag, wordnet.NOUN)      # Bulunamazsa isim kabul et

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    """Metni temizler: HTML etiketlerini siler, linkleri kaldırır, küçük harfe çevirir ve köklerine ayırır."""
    # HTML etiketlerini temizle
    soup = BeautifulSoup(text, 'lxml')
    text = soup.get_text(separator=' ')

    # URL'leri temizle
    text = re.sub(r'http\S+|www\S+|https\S+', '', text)

    # Tokenization (Kelimelere ayırma)
    tokens = word_tokenize(text.lower())

    # Stopwords temizliği, sadece alfabetik karakterler ve Lemmatizasyon (Kök bulma)
    tokens = [
        lemmatizer.lemmatize(w, get_wordnet_pos(w))
        for w in tokens if w.isalpha() and w not in stop_words
    ]

    return ' '.join(tokens)

# Metin temizleme işlemini tüm satırlara uyguluyoruz
print("Metinler temizleniyor, lütfen bekleyin...")
df['cleaned_text'] = df['Text'].apply(preprocess_text)


#......


#  Modelleme Hattı (Pipelines) Oluşturma
# LDA Modeli: Kelime frekanslarını (CountVectorizer) kullanır.
lda_pipeline = Pipeline([
    ('vectorizer', CountVectorizer(max_df=0.95, min_df=2)),
    ('lda', LatentDirichletAllocation(n_components=20, random_state=42))
])

# NMF Modeli: Kelime ağırlıklarını (TfidfVectorizer) kullanır.
nmf_pipeline = Pipeline([
    ('vectorizer', TfidfVectorizer(max_df=0.95, min_df=2)),
    ('nmf', NMF(n_components=20, random_state=42))
])

# Modelleri eğitiyoruz
print("Modeller eğitiliyor...")
lda_pipeline.fit(df['cleaned_text'])
nmf_pipeline.fit(df['cleaned_text'])

# Eğitilmiş modelleri ve vektörleştiricileri ayıklıyoruz
lda_model = lda_pipeline.named_steps['lda']
nmf_model = nmf_pipeline.named_steps['nmf']
count_vectorizer = lda_pipeline.named_steps['vectorizer']
tfidf_vectorizer = nmf_pipeline.named_steps['vectorizer']

count_data = count_vectorizer.transform(df['cleaned_text'])
tfidf_data = tfidf_vectorizer.transform(df['cleaned_text'])

#  Konuları (Topics) Görüntüleme
def display_topics(model, feature_names, n_top_words=10):
    """Her konu için en önemli kelimeleri yazdırır."""
    for idx, topic in enumerate(model.components_):
        print(f'\nTopic {idx}: ' + ' | '.join(
            [feature_names[i] for i in topic.argsort()[:-n_top_words - 1:-1]]
        ))


print('\n--- LDA Konuları ---')
display_topics(lda_model, count_vectorizer.get_feature_names_out())

print('\n--- NMF Konuları ---')
display_topics(nmf_model, tfidf_vectorizer.get_feature_names_out())


##.....




# Görselleştirme
# pyLDAvis ile interaktif LDA görselleştirmesi
pyLDAvis.enable_notebook()
lda_vis = pyLDAvis.lda_model.prepare(lda_model, count_data, count_vectorizer, n_jobs=1)


# Kelime Bulutları (WordClouds) oluşturma ve kaydetme
print("Kelime bulutları oluşturuluyor...")
def create_wordclouds(model, vectorizer, prefix):
    for idx, topic in enumerate(model.components_):
        plt.figure(figsize=(8, 4))
        wordcloud = WordCloud(width=800, height=200, background_color='white') \
            .generate(' '.join([vectorizer.get_feature_names_out()[i]
                                for i in topic.argsort()[:-30 - 1:-1]]))
        plt.imshow(wordcloud, interpolation='bilinear')
        plt.axis('off')
        plt.title(f'{prefix} Topic {idx}')
        plt.savefig(f'{prefix.lower()}_word_cloud_topic_{idx}.png', dpi=300, bbox_inches='tight')
        plt.show()


create_wordclouds(lda_model, count_vectorizer, "LDA")
create_wordclouds(nmf_model,count_vectorizer, "NMF")

# Baskın konuları ana veri çerçevesine ekleme
lda_doc_topics = lda_model.transform(count_data)
nmf_doc_topics = nmf_model.transform(tfidf_data)

df['LDA_Topic'] = lda_doc_topics.argmax(axis=1)
df['NMF_Topic'] = nmf_doc_topics.argmax(axis=1)

# Tanımladığımız etiketleri sözlük olarak ekliyoruz
lda_topic_labels = {
    0: 'Sports – International Competitions', 1: 'Royalty, Society & Public Figures',
    2: 'Sports – Rugby & Controversy', 3: 'Science, History & Miscellaneous Reports',
    4: 'Human Interest & Entertainment', 5: 'Football – Analysis & Club News',
    6: 'Covid & Health Updates', 7: 'Personal Stories & Human Interest',
    8: 'Energy, Economy & Global Affairs', 9: 'Accidents, Disasters & Health Issues',
    10: 'Sports & Business Personalities', 11: 'Tragedies & Maritime Incidents',
    12: 'UK Politics & Legal Matters', 13: 'Conflict & Refugee Crisis',
    14: 'Government Policy & Sanctions', 15: 'Entertainment & Cricket',
    16: 'Energy Prices & Covid Updates', 17: 'Culture & Identity',
    18: 'Protests & Civil Unrest', 19: 'Tennis, Celebrities & Social Issues'
}

nmf_topic_labels = {
    0: 'Covid, Science & Viral News', 1: 'Health, Sports & Environment',
    2: 'Conflict, Refugees & Global Affairs', 3: 'Terror & Human Movement',
    4: 'Health, Accidents & Human Interest', 5: 'Disasters, Politics & High-Profile Cases',
    6: 'Covid Updates & Sports', 7: 'Energy, Economy & Lifestyle',
    8: 'Sports, Accidents & Labor Issues', 9: 'Conflict, Humanitarian Crisis & Politics',
    10: 'Conflict, Sports & Human Interest', 11: 'Entertainment & International Affairs',
    12: 'Politics, Culture & Elections', 13: 'Covid Pandemic & Rules',
    14: 'Sports, Arts & International Competitions', 15: 'Covid, Royalty & Lifestyle',
    16: 'Politics, Sanctions & Refugee Policy', 17: 'History, Covid & Legal Issues',
    18: 'Social Media, Safety & Sports Tech', 19: 'Disasters, Entertainment & Personal Stories'
}

df['LDA Topic Label'] = df['LDA_Topic'].map(lda_topic_labels)
df['NMF Topic Label'] = df['NMF_Topic'].map(nmf_topic_labels)


##...

# 11. ADIM: Yeni Veri Üzerinde Test
new_text = ['''Rising natural gas prices have pushed up household energy bills, forcing families to adjust their monthly budgets. Economists warn that inflation may continue to climb, affecting spending habits and overall economic growth.''']

new_tfidf = tfidf_vectorizer.transform(new_text)
new_count = count_vectorizer.transform(new_text)

nmf_pred_topic = nmf_model.transform(new_tfidf).argmax()
lda_pred_topic = lda_model.transform(new_count).argmax()

print('\n--- Yeni Metin Tahmini ---')
print('Metin:', new_text[0][:100], "...")
print('NMF Tahmini:', nmf_topic_labels[nmf_pred_topic])
print('LDA Tahmini:', lda_topic_labels[lda_pred_topic])

#
print(" Model Tahmin Ekranı ")

def test_my_model():
    while True:
        print("\nLütfen analiz edilmesini istediğiniz haber metnini buraya yapıştırın:")
        print("(Çıkmak için sadece 'q' yazıp Enter'a basın)")

        user_text = input("> ")

        # Çıkış kontrolü
        if user_text.lower() == 'q':
            print("Test işlemi bitti!")
            break

        if len(user_text.strip()) < 5:
            print("Lütfen daha uzun bir metin girin.")
            continue

        # 1. Metin Ön İşleme
        cleaned_input = preprocess_text(user_text)

        # 2. Vektörleştirme (Sayısal verilere dönüştürme)
        input_count = count_vectorizer.transform([cleaned_input])
        input_tfidf = tfidf_vectorizer.transform([cleaned_input])

        # 3. Model Tahminleri
        # LDA Tahmini
        lda_probs = lda_model.transform(input_count)
        lda_topic_id = lda_probs.argmax()
        lda_confidence = lda_probs.max() * 100

        # NMF Tahmini
        nmf_probs = nmf_model.transform(input_tfidf)
        nmf_topic_id = nmf_probs.argmax()



        # 4. Sonuçları Yazdırma
        print("\n" + "="*50)
        print(f"📌 Girdiğiniz Metin Özet: {user_text[:70]}...")
        print("-" * 50)

        # LDA Sonucu
        lda_label = lda_topic_labels.get(lda_topic_id, "Tanımlanmamış Konu")
        print(f" LDA Tahmini: Topic {lda_topic_id} -> **{lda_label}**")
        print(f" Güven Oranı: %{lda_confidence:.2f}")

        print("-" * 50)

        # NMF Sonucu
        nmf_label = nmf_topic_labels.get(nmf_topic_id, "Tanımlanmamış Konu")
        print(f"🧬 NMF Tahmini: Topic {nmf_topic_id} -> **{nmf_label}**")
        print("="*50 + "\n")

# Fonksiyonu çalıştır
test_my_model()

# 12. ADIM: Modelleri Kaydetme
dump(lda_pipeline, 'lda_pipeline.joblib')
dump(nmf_pipeline, 'nmf_pipeline.joblib')
print("\n Modeller başarıyla 'lda_pipeline.joblib' ve 'nmf_pipeline.joblib' adıyla kaydedildi!")

# En son interaktif görseli göster
lda_vis

from google.colab import drive
drive.mount('/content/drive')
